# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.result2 = QtWidgets.QLabel(self.centralwidget)
        self.result2.setObjectName("result2")
        self.gridLayout.addWidget(self.result2, 6, 0, 1, 2)
        self.numBSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.numBSpin.setMaximum(9)
        self.numBSpin.setObjectName("numBSpin")
        self.gridLayout.addWidget(self.numBSpin, 4, 1, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 8, 0, 1, 2)
        self.numALabel = QtWidgets.QLabel(self.centralwidget)
        self.numALabel.setObjectName("numALabel")
        self.gridLayout.addWidget(self.numALabel, 3, 0, 1, 1)
        self.numLabel = QtWidgets.QLabel(self.centralwidget)
        self.numLabel.setObjectName("numLabel")
        self.gridLayout.addWidget(self.numLabel, 0, 0, 1, 1)
        self.numEditor = QtWidgets.QLineEdit(self.centralwidget)
        self.numEditor.setObjectName("numEditor")
        self.gridLayout.addWidget(self.numEditor, 1, 0, 1, 2)
        self.numASpin = QtWidgets.QSpinBox(self.centralwidget)
        self.numASpin.setMaximum(9)
        self.numASpin.setObjectName("numASpin")
        self.gridLayout.addWidget(self.numASpin, 4, 0, 1, 1)
        self.result1 = QtWidgets.QLabel(self.centralwidget)
        self.result1.setObjectName("result1")
        self.gridLayout.addWidget(self.result1, 2, 0, 1, 2)
        self.numBLabel = QtWidgets.QLabel(self.centralwidget)
        self.numBLabel.setObjectName("numBLabel")
        self.gridLayout.addWidget(self.numBLabel, 3, 1, 1, 1)
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setObjectName("errorLabel")
        self.gridLayout.addWidget(self.errorLabel, 7, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result2.setText(_translate("MainWindow", "Number starts with a and end with b"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.numALabel.setText(_translate("MainWindow", "Number a"))
        self.numLabel.setText(_translate("MainWindow", "Number"))
        self.result1.setText(_translate("MainWindow", "The first digit occurred 0 times"))
        self.numBLabel.setText(_translate("MainWindow", "Number b"))
        self.errorLabel.setText(_translate("MainWindow", ""))
