# Form implementation generated from reading ui file 'labs.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import logging
import os

from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess

logging.basicConfig(
    filename="/home/nedoletoff/Documents/tp/sample.log",
    format='%(asctime)s %(levelname)s %(message)s',
    level=logging.INFO,
    datefmt='%Y-%m-%d %H:%M:%S'
)
log = logging.getLogger("ex")



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 235)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lab3_2_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab3_2_button.setObjectName("lab3_1_button")
        self.gridLayout.addWidget(self.lab3_2_button, 2, 3, 1, 1)
        self.lab3_1_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab3_1_button.setObjectName("lab3_1_button")
        self.gridLayout.addWidget(self.lab3_1_button, 1, 3, 1, 1)
        self.lab2_1_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab2_1_button.setObjectName("lab2_1_button")
        self.gridLayout.addWidget(self.lab2_1_button, 2, 2, 1, 1)
        self.lab1_1_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab1_1_button.setObjectName("lab1_1_button")
        self.gridLayout.addWidget(self.lab1_1_button, 1, 1, 1, 1)
        self.lab1_2_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab1_2_button.setObjectName("lab1_2_button")
        self.gridLayout.addWidget(self.lab1_2_button, 2, 1, 1, 1)
        self.lab3_dop_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab3_dop_button.setObjectName("lab3_dop_button")
        self.gridLayout.addWidget(self.lab3_dop_button, 3, 3, 1, 1)
        self.lab2_dop_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab2_dop_button.setObjectName("lab2_dop_button")
        self.gridLayout.addWidget(self.lab2_dop_button, 3, 2, 1, 1)
        self.lab1_dop_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab1_dop_button.setObjectName("lab1_dop_button")
        self.gridLayout.addWidget(self.lab1_dop_button, 3, 1, 1, 1)
        self.labs1_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labs1_label.setObjectName("labs1_label")
        self.gridLayout.addWidget(self.labs1_label, 0, 1, 1, 1)
        self.labs2_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labs2_label.setObjectName("labs2_label")
        self.gridLayout.addWidget(self.labs2_label, 0, 2, 1, 1)
        self.labs3_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labs3_label.setObjectName("labs3_label")
        self.gridLayout.addWidget(self.labs3_label, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.lab1_1_button.clicked.connect(self.start_lab_1_1)
        self.lab1_2_button.clicked.connect(self.start_lab_1_2)
        self.lab1_dop_button.clicked.connect(self.start_lab_1_dop)
        self.lab2_1_button.clicked.connect(self.start_lab_2_1)
        self.lab2_dop_button.clicked.connect(self.start_lab_2_dop)
        self.lab3_1_button.clicked.connect(self.start_lab_3_1)
        self.lab3_2_button.clicked.connect(self.start_lab_3_2)
        self.lab3_dop_button.clicked.connect(self.start_lab_3_dop)


    def start_lab_1_1(self):
        subprocess.run(['python3', 'p1/first/main.py'])
    def start_lab_1_2(self):
        subprocess.run(['python3', 'p1/second/main.py'])
    def start_lab_1_dop(self):
        subprocess.run(['python3', 'p1/dop/main.py'])
    def start_lab_2_1(self):
        subprocess.run(['python3', 'p2/first/main.py'])
    def start_lab_2_dop(self):
        subprocess.run(['python3', 'p2/dop/main.py'])
    def start_lab_3_1(self):
        subprocess.run(['python3', 'p3/first/main.py'])
    def start_lab_3_2(self):
        subprocess.run(['python3', 'p3/second/main.py'])
    def start_lab_3_dop(self):
        subprocess.run(['python3', 'p3/dop/main.py'])
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab3_1_button.setText(_translate("MainWindow", "Lab3.1"))
        self.lab2_1_button.setText(_translate("MainWindow", "Lab2.1"))
        self.lab1_1_button.setText(_translate("MainWindow", "Lab1.1"))
        self.lab1_2_button.setText(_translate("MainWindow", "Lab1.2"))
        self.lab3_dop_button.setText(_translate("MainWindow", "Lab3.dop"))
        self.lab2_dop_button.setText(_translate("MainWindow", "Lab2.dop"))
        self.lab1_dop_button.setText(_translate("MainWindow", "Lab.1.dop"))
        self.lab3_2_button.setText(_translate("MainWindow", "Lab3.2"))
        self.labs1_label.setText(_translate("MainWindow", "Labs 1"))
        self.labs2_label.setText(_translate("MainWindow", "Labs 2"))
        self.labs3_label.setText(_translate("MainWindow", "Labs 3"))


if __name__ == "__main__":
    import sys
    try:
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec())
    except Exception as e:
        log.exception(e)
