# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.result = QtWidgets.QTextBrowser(self.centralwidget)
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 9, 0, 1, 2)
        self.changeButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeButton.setObjectName("changeButton")
        self.gridLayout.addWidget(self.changeButton, 14, 0, 1, 2)
        self.rest = QtWidgets.QTextBrowser(self.centralwidget)
        self.rest.setObjectName("rest")
        self.gridLayout.addWidget(self.rest, 4, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.surnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.surnameLabel.setObjectName("surnameLabel")
        self.gridLayout.addWidget(self.surnameLabel, 0, 1, 1, 1)
        self.surnameUnicode = QtWidgets.QTextBrowser(self.centralwidget)
        self.surnameUnicode.setObjectName("surnamenicode")
        self.gridLayout.addWidget(self.surnameUnicode, 6, 0, 1, 1)
        self.surnameEditor = QtWidgets.QLineEdit(self.centralwidget)
        self.surnameEditor.setObjectName("surnameEditor")
        self.gridLayout.addWidget(self.surnameEditor, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setObjectName("errorLabel")
        self.gridLayout.addWidget(self.errorLabel, 13, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("error_label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.secondNameEditor = QtWidgets.QLineEdit(self.centralwidget)
        self.secondNameEditor.setObjectName("secondNameEditor")
        self.gridLayout.addWidget(self.secondNameEditor, 2, 1, 1, 1)
        self.nameEditor = QtWidgets.QLineEdit(self.centralwidget)
        self.nameEditor.setObjectName("nameEditor")
        self.gridLayout.addWidget(self.nameEditor, 1, 0, 1, 1)
        self.nameUnicode = QtWidgets.QTextBrowser(self.centralwidget)
        self.nameUnicode.setObjectName("nameUnicode")
        self.gridLayout.addWidget(self.nameUnicode, 4, 0, 1, 1)
        self.secondNameUnicode = QtWidgets.QTextBrowser(self.centralwidget)
        self.secondNameUnicode.setObjectName("secondNameUnicode")
        self.gridLayout.addWidget(self.secondNameUnicode, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.changeButton.setText(_translate("MainWindow", "Run"))
        self.nameLabel.setText(_translate("MainWindow", "Имя"))
        self.surnameLabel.setText(_translate("MainWindow", "Фамилия"))
        self.label_4.setText(_translate("MainWindow", "Отчество"))
        self.errorLabel.setText(_translate("MainWindow", "Error"))
        self.label.setText(_translate("MainWindow", "UNICODE "))
        self.label_2.setText(_translate("MainWindow", "Остаток строки"))
        self.label_3.setText(_translate("MainWindow", "Результат"))
